# .kodiak.toml
[merge]
automerge_label = "automerge"

[merge.automerge_dependencies]
# auto merge all PRs opened by "dependabot"
versions = ["major", "minor", "patch"]
usernames = ["dependabot"]

# if using `update.always`, add dependabot to `update.ignore_usernames` to allow
# dependabot to update and close stale dependency upgrades.
[update]
ignored_usernames = ["dependabot"]
